// This file is generated by Slice Machine. Update with care!

import Accordion from './Accordion';
import Boolean from './Boolean';
import Image from './Image';
import Sites from './Sites';
import Text from './Text';

export {
	Accordion,
	Boolean,
	Image,
	Sites,
	Text,
};

export const components = {
	accordion: Accordion,
	boolean: Boolean,
	image: Image,
	sites: Sites,
	text: Text,
};
